import React, { useEffect, useState } from "react";
import { WebService } from "../../services";
import moment from "moment";

import "./GiveCreditsPage.scss";

function GiveCreditsPage() {
    const [recipientEmail, setRecipientEmail] = useState("");
    const [amount, setAmount] = useState("");

    // TODO: use fetchDelegates to get delegates and transfer if already exists

    const transfer = () => {
      if (recipientEmail && amount) {
        WebService.postDelegates({
          user: {
            password: Math.random().toString(36).substr(2, 8), // not secure but this password doesn't have to be 
            email: recipientEmail
          },
          is_autogenerated: true,
          invited_by: WebService.userobj.id
        }).subscribe(async (data) => {
          if (data.ok) {
            const recipient = await data.json();
            WebService.postTransfer({
              sender: WebService.userobj.id,
              recipient: recipient.id,
              amount: amount,
              date: moment().toISOString(),
              process: 1 // ???
            }, recipient.id).subscribe(async (data) => {
              if (data.ok) {
                // TODO: stuff here on transfer completion
              } else {
                const error = await data.json();
                console.log(error);
              }
            });
          } else {
            const error = await data.json();
            console.log(error);
          }
        });
      }
    };

    return (
        <div className="give-credits-page">

        </div>
    );
}

export default GiveCreditsPage;
