import React from "react";
import { WebService, Password } from "../../services";
import moment from "moment";

import "./GiveCreditsPage.scss";

function GiveCreditsPage() {
    const [recipientEmail, setRecipientEmail] = useState("");
    const [amount, setAmount] = useState("");

    useEffect(() => {
      props.changeColor(BgColor.White);

     // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const transfer = () => {
      if (recipientEmail && amount) {
        WebService.postDelegates({
          user: {
            password: Password.password.generate(32),
            email: recipientEmail
          },
          is_autogenerated: true,
          invited_by: sessionStorage.getItem("user").id
        }).subscribe(async (data) => {
          if (data.ok) {
            const recipient = await data.json();
            WebService.postTransfer({
              sender: sessionStorage.getItem("user").id,
              recipient: recipient.id,
              amount: amount,
              date: moment.format(),
              process: 1 // ???
            }).subscribe(async (data) => {
              if (data.ok) {
                // TODO: stuff here on transfer completion
              } else {
                const error = await data.json();
                console.log(error);
              }
            });
          } else {
            const error = await data.json();
            console.log(error);
          }
        });
      }
    };

    return (
        <div className="give-credits-page">

        </div>
    );
}

export default GiveCreditsPage;
