from django.contrib.auth.models import User
from main.models import Delegate
from django.conf import settings
import os

adminuser, created = User.objects.update_or_create(
                        username="admin",
                        email=os.environ.get('ADMIN_EMAIL'),
                        is_staff=True,
                        is_superuser=True)

adminuser.set_password(os.environ.get('ADMIN_PASSWORD'))
adminuser.save()

admin, created = Delegate.objects.update_or_create(
                    user=adminuser,
                    is_autogenerated=False,
                    invited_by=None,
                    credit_balance=99)

admin.save()
