# Generated by Django 3.1.2 on 2020-12-23 18:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('groups', models.ManyToManyField(blank=True, default=[], to='auth.Group')),
            ],
            options={
                'permissions': [('can_view', 'Can view')],
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_autogenerated', models.BooleanField(blank=True, default=False)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('credit_balance', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.delegate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('negative_votes', models.BooleanField(default=True)),
                ('matching_pool', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('vote_token', models.TextField(blank=True, default='../../../frontend/public/black-square.png')),
                ('num_tokens', models.DecimalField(blank=True, decimal_places=0, default=99, max_digits=4)),
                ('groups', models.ManyToManyField(blank=True, default=[], to='auth.Group')),
            ],
            options={
                'permissions': [('can_vote', 'Can vote'), ('can_view_results', 'Can view results')],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('matching_pool', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('curation_info', models.TextField(blank=True)),
                ('top_posts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=140), blank=True, size=None)),
                ('conversation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.conversation')),
                ('delegates', models.ManyToManyField(blank=True, default=[], to='main.Delegate')),
                ('election', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.election')),
                ('groups', models.ManyToManyField(blank=True, default=[], to='auth.Group')),
            ],
            options={
                'permissions': [('can_view', 'Can view')],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=512)),
                ('sum_contributions', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('current_match', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('num_contributors', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.election')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('date', models.DateTimeField(null=True)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.proposal')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('C', 'Canceled')], default='P', max_length=1)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.process')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
