# Generated by Django 3.1.2 on 2020-10-26 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('profile_pic', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('oauth_uuid', models.CharField(blank=True, max_length=256, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(default='user not found', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, to_field='email')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('negative_votes', models.BooleanField(default=True)),
                ('matching_fund', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('vote_token', models.TextField()),
                ('num_tokens', models.DecimalField(decimal_places=0, default=99, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=512)),
                ('sum_contributions', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('current_match', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('num_contributors', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('election_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.election')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=4)),
                ('date', models.DateField()),
                ('proposal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.proposal')),
                ('sender', models.ForeignKey(default='user not found', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
