# Generated by Django 3.1.2 on 2020-11-16 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.TextField(null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('credit_balance', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.delegate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('negative_votes', models.BooleanField(default=True)),
                ('matching_fund', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('vote_token', models.TextField(default='../../../frontend/public/black-square.png')),
                ('num_tokens', models.DecimalField(decimal_places=0, default=99, max_digits=4)),
            ],
            options={
                'permissions': [('can_vote', 'Can vote'), ('can_view_results', 'Can view results')],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=512)),
                ('sum_contributions', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('current_match', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('num_contributors', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.election')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('date', models.DateTimeField(null=True)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.proposal')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.delegate')),
            ],
        ),
    ]
