# Generated by Django 3.1.2 on 2021-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('Initialization', 'Initialization'), ('Delegation', 'Delegation'), ('Deliberation', 'Deliberation'), ('Curation', 'Curation'), ('Election', 'Election'), ('Result', 'Result')], default='Initialization', max_length=14),
        ),
    ]
