# Generated by Django 3.1.2 on 2021-01-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='uuid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
