# Generated by Django 3.1.2 on 2020-12-30 08:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='curation_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='matching_pool',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='top_posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=140), blank=True, null=True, size=None),
        ),
    ]
