# Generated by Django 3.1.2 on 2020-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
