# Generated by Django 3.1.2 on 2021-01-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delegate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='recipient',
            field=models.EmailField(default='al@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
