# Generated by Django 3.1.2 on 2021-01-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='conversation',
            name='uuid',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='oauth_provider',
            field=models.CharField(choices=[('git', 'Github'), ('twt', 'Twitter')], default='git', max_length=3),
        ),
        migrations.AddField(
            model_name='delegate',
            name='oauth_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='public_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('Introduction', 'Introduction'), ('Delegation', 'Delegation'), ('Deliberation', 'Deliberation'), ('Curation', 'Curation'), ('Election', 'Election'), ('Result', 'Result')], default='Introduction', max_length=14),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
