# Generated by Django 3.1.2 on 2020-11-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_auto_20201116_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='is_autogenerated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='groups',
            field=models.ManyToManyField(blank=True, default=[], to='auth.Group'),
        ),
    ]
