# Generated by Django 3.1.2 on 2021-01-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210104_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='uuid',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
