# Generated by Django 3.1.2 on 2020-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201026_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='vote_token',
            field=models.TextField(default='../../../frontend/public/black-square.png'),
        ),
    ]
