# Generated by Django 3.1.2 on 2020-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201026_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='election_id',
            new_name='election',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='proposal_id',
            new_name='proposal',
        ),
    ]
