# Generated by Django 3.1.2 on 2021-01-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_conversation_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='uuid',
        ),
        migrations.AddField(
            model_name='proposal',
            name='votes_received',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
    ]
