# Generated by Django 3.1.2 on 2021-01-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210118_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='uuid',
        ),
    ]
