# Generated by Django 3.1.2 on 2021-01-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_delegate_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='delegate',
            name='oauth_provider',
            field=models.CharField(choices=[('git', 'Github'), ('twt', 'Twitter')], default='git', max_length=3),
        ),
        migrations.AddField(
            model_name='delegate',
            name='oauth_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='public_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
