# Generated by Django 3.1.2 on 2020-11-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201027_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
