# Generated by Django 3.1.2 on 2020-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_auto_20201116_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('groups', models.ManyToManyField(blank=True, default=[], to='auth.Group')),
            ],
            options={
                'permissions': [('can_view', 'Can view')],
            },
        ),
    ]
