# Generated by Django 3.1.2 on 2020-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201102_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
