# Generated by Django 3.1.2 on 2021-01-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210120_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='recipient',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
