# Generated by Django 3.1.2 on 2021-01-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210121_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='uuid',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
