# Generated by Django 3.1.2 on 2020-12-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_conversation_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='site_id',
        ),
    ]
