# Generated by Django 3.1.2 on 2020-11-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201102_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.election'),
        ),
    ]
