# Generated by Django 3.1.2 on 2021-01-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_conversation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('Introduction', 'Introduction'), ('Delegation', 'Delegation'), ('Deliberation', 'Deliberation'), ('Curation', 'Curation'), ('Election', 'Election'), ('Result', 'Result')], default='Introduction', max_length=14),
        ),
    ]
