# Generated by Django 3.1.2 on 2020-11-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201105_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
