# Generated by Django 3.1.2 on 2020-11-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201109_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.election'),
        ),
    ]
