# Generated by Django 3.1.2 on 2020-11-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201109_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonVoter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('password', models.TextField(unique=True)),
                ('voted', models.BooleanField(default=False)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.election')),
            ],
        ),
    ]
