# Generated by Django 3.1.2 on 2020-11-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_anonvoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonvoter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
