# Generated by Django 3.1.2 on 2020-11-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201109_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonvoter',
            name='password',
        ),
        migrations.AddField(
            model_name='anonvoter',
            name='name',
            field=models.CharField(default='alex', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonvoter',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anonvoter',
            name='voted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
