# Generated by Django 3.1.2 on 2020-11-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201110_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonvoter',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
