# Generated by Django 3.1.2 on 2020-11-10 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_election_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='election',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.election'),
        ),
    ]
