# Generated by Django 3.1.2 on 2020-11-12 20:36

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0021_user_voted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'permissions': [('can_vote', 'Can vote'), ('can_view_results', 'Can view results')]},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='election',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='null', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='election',
            name='group',
        ),
        migrations.AddField(
            model_name='election',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='AnonVoter',
        ),
    ]
