# Generated by Django 3.1.2 on 2020-11-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201113_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth_uuid',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(null=True),
        ),
    ]
