# Generated by Django 3.1.2 on 2020-11-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201113_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='group',
            new_name='groups',
        ),
    ]
